entities:
  bob:
    policies:
      - default
    metadata:
      email: bob@barker.com
  sir:
    policies:
      - default
    metadata:
      email: sir@smokesalot.com

users:
  bob:
    password: barker
  sir:
    password: smokesalot

groups:
  admins:
    type: internal
    entity_names:
      - bob
    policies:
      - ui
  chumps:
    type: internal
    policies:
      - default
    entity_names: []

kubernetes:
  cluster:
    auth_endpoint: kubernetes
    default_lease_ttl: 60s
  roles:
    argo_oidc_client:
      kubernetes:
        service_account_names:
          - argo-workflows-server
        namespaces:
          - argo-workflows
      token_policies:
        - argo_workflows_oidc_client

secrets:
  kubernetes:
    default_lease_ttl_seconds: 60
    max_lease_ttl_seconds: 120
    roles:
      list-pods:
        allowed_kubernetes_namespaces: ["*"]
        kubernetes_role_type: ClusterRole
        token_max_ttl: 600     # 10 minutes
        token_default_ttl: 600 # 10 minutes
        generated_role_rules: |
          rules:
          - apiGroups: ["*"]
            resources: [namespaces, pods]
            verbs: [get,list]
