entities:
  bob:
    policies:
      - default
    metadata:
      email: bob@barker.com
  sir:
    policies:
      - default
    metadata:
      email: sir@smokesalot.com

users:
  bob:
    password: barker
  sir:
    password: smokesalot

groups:
  admins:
    type: internal
    entity_names:
      - bob
    policies:
      - ui
  chumps:
    type: internal
    policies:
      - default
    entity_names: []

kubernetes:
  cluster:
    auth_endpoint: kubernetes/client_cluster
    default_lease_ttl: 60s
  roles:
    argo_oidc_client:
      kubernetes:
        service_account_names:
          - argo-workflows-server
        namespaces:
          - argo-workflows
      token_policies:
        - argo_workflows_oidc_client
