entities:
  bob:
    policies:
      - default
    metadata:
      email: bob@barker.com
  sir:
    policies:
      - default
    metadata:
      email: sir@smokesalot.com

users:
  bob:
    password: barker
    token_type: service
  sir:
    password: smokesalot
    token_type: service

groups:
  admins:
    type: internal
    entity_names:
      - bob
    policies:
      - ui
      - list_pods
  chumps:
    type: internal
    policies:
      - default
    entity_names: []

pki_backend:
  auth_endpoint: pki
  default_lease_ttl_seconds: 600
  max_lease_ttl_seconds: 3600
  common_name: cluster.local
  roles:
    list_pods:
      identity: list-pods

cert:
  endpoint: cert
  default_lease_ttl: 60s
  # these will be configured in taskfiles rather than in main hydration
  roles:
    list_pods:
      allowed_dns_sans: []
        # - list-pods.svc
      token_type: service

kubernetes:
  cluster:
    auth_endpoint: kubernetes
    default_lease_ttl: 60s
  roles:
    argo_oidc_client:
      kubernetes:
        service_account_names:
          - argo-workflows-server
        namespaces:
          - argo-workflows
      token_policies:
        - argo_workflows_oidc_client

secrets:
  kubernetes:
    default_lease_ttl_seconds: 600
    max_lease_ttl_seconds: 3600
    roles:
      list-pods:
        allowed_kubernetes_namespaces: ["*"]
        kubernetes_role_type: ClusterRole
        token_max_ttl: 600     # 10 minutes
        token_default_ttl: 600 # 10 minutes
        generated_role_rules: |
          rules:
          - apiGroups: ["*"]
            resources: [namespaces, pods]
            verbs: [get,list]
