auth:
  kubernetes:
    name: dev
  approle:
    name: approle
  cert:
    name: cert
  userpass:
    name: userpass
    users:
      - name: admin
        password: admin

entities:
  bob:
    policies:
      - default
    metadata:
      email: bob@barker.com
  sir:
    policies:
      - default
    metadata:
      email: sir@smokesalot.com
